<a name="top"></a>Overview: Matrices
===

* [Matrices](#matrizen)
  * [Multi-dimensional lists](#listen)
  * [NumPy Arrays](#arrays)
  * [Creating Arrays](#erstellen)
  * [Maths on Arrays](#mathe)
  * [Filters](#filter)
* [Exercies 07: Matrices](#uebung07)

**Learning Goals:** After this lecture you
* know what a third party library is and how to use it
* can save multi-dimensional data in arrays
* can use simple maths and filtering on arrarys
* know how to save and load arrays in files

<a name="matrizen"></a>Matrices
===

Until now, we were only looking at one-dimensional data containers:

In [2]:
list = [1, 2, 3, 4, 5]

So, what do we do to create a matrix?
\begin{equation*}
A = \begin{pmatrix} 1 & 2  & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix}
\end{equation*}  

<a name="listen"></a>Multi-dimensional lists
---

In theory, we can use nested lists as a matrix equivalent:

In [3]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Accessing single list elements isn't too hard:

In [4]:
print(A[1][1])

5


However, getting equivalent functionality as slicing is quite comlicated already.
Remember, for one-dimensional lists, it works like this:

In [5]:
a = [1, 2, 3, 4, 5]
print(a[2:4])

[3, 4]


[top](#top)

<a name="arrays"></a>NumPy Arrays
---

[a more detailed introduction to NumPy can be found here https://docs.scipy.org/doc/numpy-dev/user/quickstart.html]

To solve this issue, we can use a _third party library_. In contrast to the Python standard libraries, this typ of library is not included in every Python installation, but has to be installed manually.

However, many scientific Python distributions (for example Anaconda) already include most of the important third party libraries. Our installation is no exception to this rule.

For multi-dimensional lists (called _arrays_) we need a library called ```NumPy``` (numeric Python).
Since it is installed already, we can simply import NumPy into our script:

In [6]:
# the keyword 'as' assigns the keyword 'np' to 'numpy' 
# while importing it - this makes our code shorter and more readable
import numpy as np

In [7]:
# convert the nested list A to a NumPy array using the asarray() function
B = np.asarray(A)

# display A and B to compare
print('Nested list:\n {}\n'.format(A))
print('NumPy nD-array:\n {}'.format(B))

Nested list:
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

NumPy nD-array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


We can access elements of multi-dimensional arrays using multiple indices (one per dimension of the array):

In [8]:
print(B[1,1])

5


Doesn't seem that impressive, but we can use slicing again! Thus, we can make multi-dimensional slice:

In [9]:
print(B[0:2, 0:2])  # [row, column]

[[1 2]
 [4 5]]


In [78]:
print(B[0:, 0:2])  # [row, column]

[[1 2]
 [4 5]
 [7 8]]


In [11]:
print(B[0:2, 0:])  # [row, column]

[[1 2 3]
 [4 5 6]]


**Important:** The order of indices is important, as you can see above!

[top](#top)

<a name="erstellen"></a>Creating Arrays
---

We have seen that we can convert a container into an array using the ```asarray()``` function.
There are a lot more functions that allow us to create arrays. Let's take a look at three quite handy ones:

* ```arange()```: same as ```range()```, but as an array.
* ```reshape()```: changes the form of an array.
* ```linspace()```: similar to ```arange()```, but doesn't create integers. Instead it fills the array with a linear interpolation between start and end.

In [12]:
# create a 1-d array with 16 elements
A = np.arange(16)
print(A)
print(type(A))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
<class 'numpy.ndarray'>


In [13]:
# reshape A to a quadratic 2-d array
A = A.reshape((4,4))
print(A)

# note: the number of elements has to be the same!

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [14]:
start = 0
stop = 10
number = 50

# linspace creates a 'number' of elements, uniformly distibuted
# between start and stop 
B = np.linspace(start, stop, number)  # (start, stop, number)

print(B)

[  0.           0.20408163   0.40816327   0.6122449    0.81632653
   1.02040816   1.2244898    1.42857143   1.63265306   1.83673469
   2.04081633   2.24489796   2.44897959   2.65306122   2.85714286
   3.06122449   3.26530612   3.46938776   3.67346939   3.87755102
   4.08163265   4.28571429   4.48979592   4.69387755   4.89795918
   5.10204082   5.30612245   5.51020408   5.71428571   5.91836735
   6.12244898   6.32653061   6.53061224   6.73469388   6.93877551
   7.14285714   7.34693878   7.55102041   7.75510204   7.95918367
   8.16326531   8.36734694   8.57142857   8.7755102    8.97959184
   9.18367347   9.3877551    9.59183673   9.79591837  10.        ]


Additionally, we can load arrays from files or save them as such:
* ```np.loadtxt()```
* ```np.savetxt()```

In [16]:
polygone = np.loadtxt('polygons.txt')
print(polygone)

[[ 2.93524537  2.9328648   2.93049891 ...,         nan         nan
          nan]
 [ 2.934738    2.93261704  2.93027465 ...,         nan         nan
          nan]
 [ 2.93613947  2.93298815  2.9306612  ...,         nan         nan
          nan]
 ..., 
 [ 2.962692    2.962387    2.963455   ...,  3.007614    3.003555    2.99913   ]
 [ 2.960098    2.959122    2.963394   ...,  3.012039    3.011398    3.010513  ]
 [ 2.960251    2.958511    2.961594   ...,  3.009201    3.011093    3.009872  ]]


If an array is so big that direct visual display is not helpful, we can find out its size by using an _attribut_ of the array-object - ```shape```:

In [17]:
print(polygone.shape)

(1091, 1051)


In [20]:
# shape is a tupel, an iterable container similar to a list
# it has two values that we can access
height, width = polygone.shape

print('Number of rows: {}'.format(height))
print('Number of columns: {}'.format(width))

Number of rows: 1091
Number of columns: 1051


Saving an array into a file is about as easy as loading one from a file:

In [22]:
np.savetxt('array_b.txt', B)

[top](#top)

<a name="mathe"></a>Maths on Arrays
---

Standard operations, like addition, subtraction, multiplication or division on arrays are interpreted _element wise_ on every element of the array:

In [23]:
A = np.arange(16).reshape((4,4))

print('before:')
print(A)
A = A + 2
print('\nafter:')
print(A)

before:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

after:
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


This does not work with normal lists!

In [24]:
a = [1, 2, 3, 4]
a + 2

TypeError: can only concatenate list (not "int") to list

Normal matrix-multiplication can be done by using the ```dot()``` function:

In [32]:
# create two 3x3 matrices from arrays
A = np.asarray([[1, 2, 3], [0, 1, 0], [2, 0, 1]])
B = np.asarray([[3, 0, 4], [0, 0, 1], [2, 2, 2]])

# multiplicate the matrices and save the result
C = np.dot(A, B)

# check the result
print('A:')
print(A)
print('\nB:')
print(B)
print('\nC:')
print(C)

A:
[[1 2 3]
 [0 1 0]
 [2 0 1]]

B:
[[3 0 4]
 [0 0 1]
 [2 2 2]]

C:
[[ 9  6 12]
 [ 0  0  1]
 [ 8  2 10]]


[top](#top)

<a name="filter"></a>Filters
---

We can also use logical function on arrays to _filter_ them. The corresponding function is ```where()```:

In [33]:
# which of the elements is smaller than 10?
# where returns the indices of the elements that fulfill the condtion
np.where(C < 10)

(array([0, 0, 1, 1, 1, 2, 2]), array([0, 1, 0, 1, 2, 0, 1]))

In [34]:
# which elements in C are smaller than 10?
C[np.where(C < 10)]

array([9, 6, 0, 0, 1, 8, 2])

In [36]:
# filter C such that every element smaller 10
# is set to 0 and all other to 1
D = np.where(C < 10, 0, 1)
print(D)

[[0 0 1]
 [0 0 0]
 [0 0 1]]


[top](#top)

<a name="uebung07"></a>Exercies 07: Matrices
===

1. **Matrices**
  1. Create a list of 100 random integers. Convert this list to a NumPy array and reshape it to a 10x10 matrix.
  2. Save this matrix in a text file.
  3. **(Optional)** Investigate how you can write this much shorter, using ```numpy.random.randint()```.
  4. Set the 5x5 sub-matrices in each corner of the 10x10 matrix to different variables.
  5. Multiply those sub-matrices and display the result.
  6. **(Optional)** Experiment a bit using the filter function ```where()```. Which type of logical statments can be used? How about operations? Saving elemtents of two matrixes into a third one?

[top](#top)