<a name="loesung07"></a>Lösung Übung 07
===

In [1]:
# 1.a
# import random and numpy
# note: call numpy using 'np'
import random
import numpy as np

# create a list of 100 random integers between 0 and 100
numbers = [random.randint(0,101) for i in range(100)]
# convert the list to an array
numbers = np.asarray(numbers)
# "reshape" the 1-d array to a 2-d 10x10 matrix
numbers = numbers.reshape((10,10))
print(numbers)

[[ 64  54  67   1  31  95  63  41  43  91]
 [ 58  96  78  35  15  51  24  99   4  62]
 [ 22  92  60  20  86  55  12  96  69  14]
 [ 48  87  59  47  70  36  92  51  30  65]
 [ 66  79  11 100  12  22  22  43  62  83]
 [ 82  33  59  99  48   7  44  54  93  57]
 [ 12  87  91  57  18  62  45  27  97   4]
 [ 11  30  81  63  49  86  74  85  29  69]
 [ 43  99  56  20  10  64  51   4  44  65]
 [ 38  24  43  17  94  30  41  97  89  58]]


In [2]:
# 1.b
np.savetxt('random-numbers.txt', numbers)

In [3]:
# 1.c
# Documentation to numpy.random.randint:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html

numbers = np.random.randint(0, 101, (10,10))
print(numbers)

[[31 29 55  0 72 39  8 75 55 65]
 [31 80 25 25 70 40 71 95 85 14]
 [ 9 30 34 31 98 83 27 12 42 72]
 [22 41 41 30  7 25  6 84 76 18]
 [81 29 76 93 85 71 80 60 43 22]
 [19 23 60 14 13  5 11 40  3 43]
 [28 99 11 24 48 15 50 97 45 10]
 [11  8 81 16 25 78 96 39  7 55]
 [23  2  9 38 30  9 93 65  2 11]
 [35  6 78 53  5 95 49 66 38 72]]


In [4]:
# 1.d
print('upper left:')
upper_left = numbers[0:5, 0:5]
print(upper_left)
print('upper right:')
upper_right = numbers[0:5, 5:]
print(upper_right)
print('down left:')
down_left = numbers [5:, 0:5]
print(down_left)
print('down right:')
down_right = numbers[5:, 5:]
print(down_right)

upper left:
[[31 29 55  0 72]
 [31 80 25 25 70]
 [ 9 30 34 31 98]
 [22 41 41 30  7]
 [81 29 76 93 85]]
upper right:
[[39  8 75 55 65]
 [40 71 95 85 14]
 [83 27 12 42 72]
 [25  6 84 76 18]
 [71 80 60 43 22]]
down left:
[[19 23 60 14 13]
 [28 99 11 24 48]
 [11  8 81 16 25]
 [23  2  9 38 30]
 [35  6 78 53  5]]
down right:
[[ 5 11 40  3 43]
 [15 50 97 45 10]
 [78 96 39  7 55]
 [ 9 93 65  2 11]
 [95 49 66 38 72]]


In [11]:
# 1.e
matrix_product = np.dot(upper_left, upper_right)
print(matrix_produkt)

# the same for the other multiplications

[[ 1287  1335  2412  1811  2457]
 [12179 11281 13762 11129 15337]
 [ 9011 10544 14659 11243 13953]
 [14376 18185 17623 11645 21225]
 [ 9823 12048 19179 12594 17692]]


In [5]:
# 1.f
# create a new matrix
# take a look in the matrix upper_right:
# if upper_right > 50, take an element from down_left
# if upper_right < 50, nim ein Element aus down_right
new_matrix = np.where(upper_right > 50, down_left, down_right)
print(new_matrix)

[[ 5 11 60 14 13]
 [15 99 11 24 10]
 [11 96 39  7 25]
 [ 9 93  9 38 11]
 [35  6 78 38 72]]
