<a name="loesung07"></a>Solutions exercise 07
===

In [1]:
# 1.a
# import random and numpy
# note: call numpy using 'np'
import random
import numpy as np

# create a list of 100 random integers between 0 and 100
numbers = [random.randint(0,101) for i in range(100)]
# convert the list to an array
numbers = np.asarray(numbers)
# "reshape" the 1-d array to a 2-d 10x10 matrix
numbers = numbers.reshape((10,10))
print(numbers)

[[ 43  52  76  15  11  48  12  16  13  45]
 [ 19  86  32  62  94  78  69   9  98  81]
 [ 89  17  26  42  80  53   4  95  25  92]
 [ 49  30  72  12  83  99  15   9  13  86]
 [ 71   2  72  59  48  48  77  24  73  87]
 [ 10  65  88  24  18   6  97  73   0  69]
 [100   1  14  77  89  15  84  12  37   5]
 [ 21  44  86  66   7  37 101  49  92  67]
 [  0  48  80  28  50  67  32  64  29  73]
 [ 81  79  77  97   6  82   1  16  23  27]]


In [2]:
# 1.b
np.savetxt('random-numbers.txt', numbers)

In [3]:
# 1.c
# Documentation to numpy.random.randint:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html

numbers = np.random.randint(0, 101, (10,10))
print(numbers)

[[65 29  4 80 24 51 68 25  9  5]
 [54 51 20  0  5 96 62 35 99 46]
 [76 40 35 93 62 55 67 60 16 75]
 [40 51 11 87 11 18 86 50 14 16]
 [30 26 59 43 30 14  4 26 91 52]
 [48  8 78 56 40 29 94  1 79 95]
 [23 36 91 99 38  5 68 24 75 59]
 [71 53 41 24 73 29 35 20  4 12]
 [10 34 54 51 22 81 98 90 19 46]
 [57 25 36 96 56 50 86 70 60 92]]


In [4]:
# 1.d
print('upper left:')
upper_left = numbers[:5, :5]
print(upper_left)
print('upper right:')
upper_right = numbers[:5, 5:]
print(upper_right)
print('lower left:')
down_left = numbers [5:, :5]
print(down_left)
print('lower right:')
down_right = numbers[5:, 5:]
print(down_right)

upper left:
[[65 29  4 80 24]
 [54 51 20  0  5]
 [76 40 35 93 62]
 [40 51 11 87 11]
 [30 26 59 43 30]]
upper right:
[[51 68 25  9  5]
 [96 62 35 99 46]
 [55 67 60 16 75]
 [18 86 50 14 16]
 [14  4 26 91 52]]
lower left:
[[48  8 78 56 40]
 [23 36 91 99 38]
 [71 53 41 24 73]
 [10 34 54 51 22]
 [57 25 36 96 56]]
lower right:
[[29 94  1 79 95]
 [ 5 68 24 75 59]
 [29 35 20  4 12]
 [81 98 90 19 46]
 [50 86 70 60 92]]


In [5]:
# 1.e
matrix_product = np.dot(upper_left, upper_right)
print(matrix_product)

# the same for the other multiplications

[[ 8095 13462  7504  6824  4487]
 [ 8820  8194  4465  6310  4376]
 [12183 18239 11662 12148  9557]
 [ 9261 14145  8081  7804  5335]
 [ 8465 11423  8130  7120  8019]]


In [6]:
# 1.f
# create a new matrix
# take a look in the matrix upper_right:
# if upper_right > 50, take an element from lower_left
# if upper_right < 50, take an element from lower_right
new_matrix = np.where(upper_right > 50, down_left, down_right)
print(new_matrix)

[[48  8  1 79 95]
 [23 36 24 99 59]
 [71 53 41  4 73]
 [81 34 90 19 46]
 [50 86 70 96 56]]
